### ISSUE TITLE
Facebook login is not possible for new users

### ISSUE THREAD

**Issue by Ross-Gibson** [react-native-market/firebase-authentication-kit#10]
Hello, I have an issue with my purchase (qOuutZdDkbgJcNW0UVXJ), here are the details of my issue:

In `src/providers/Facebook.tsx` the function `handleFacebook` blocks the possibility of creating a new user via Facebook. At line 21 the `if (!loading && user)` will always be false because `user` is `null` for new installs.

To resolve this issue update the function the following:

```javascript
 async function handleFacebook() {
    if (!loading) {
      setLoading(true);

      try {
        if (variant === 'UNLINK' && user) {
          await user.unlink(PROVIDER_ID);
        } else {
          const {isCancelled} = await LoginManager.logInWithPermissions([
            'public_profile',
          ]);

          if (isCancelled) {
            Alert.alert('Facebook Auth Canceled');
          } else {
            const result = await AccessToken.getCurrentAccessToken();
            if (!result) {
              throw new Error(
                'No Access Token was returned from Facebook SDK.',
              );
            }

            const {accessToken} = result;

            const credential = auth.FacebookAuthProvider.credential(
              accessToken,
            );

            if (variant === 'LINK' && user) {
              await user.linkWithCredential(credential);
            } else if (variant === 'SIGN_IN') {
              await auth().signInWithCredential(credential);
            }
          }
        }
      } catch (error) {
        Alert.alert('Facebook Auth Error', error.message);
      } finally {
        setLoading(false);
      }
    }
  }
```

**Comment by missklorina** [comment]
Hi, with this code, the user created with facebook don't have the facebook mail associated with the firebase user.

**Comment by Ross-Gibson** [comment]
Hey @missklorina if you'd like to have the email too, then you'll need to get permission from the user to access this data from their profile. To do that, simply add `email` to the list of requested permissions.

Like this:

```javascript
const { isCancelled } = await LoginManager.logInWithPermissions([
            'public_profile',
            'email',
          ]);
```

**Comment by missklorina** [comment]
@Ross-Gibson 
thanks, now the email is added correctly.

**Comment by Salakar** [comment]
Hey @Ross-Gibson thanks for reporting this and for the code example to fix it, this will be available in the next update in a few days.

I've given you a 50% refund as a thanks
