### ISSUE TITLE
Cancelling Google sign in on iOS gives wrong error code

### ISSUE THREAD

**Issue by Ross-Gibson** [react-native-market/firebase-authentication-kit#11]
Hello, I have an issue with my purchase (qOuutZdDkbgJcNW0UVXJ), here are the details of my issue:

This is a [known issue](https://github.com/googlesamples/google-services/issues/426)

For now, the solution is to update the switch statement in `src/providers/Google.tsx` to include the correct cancel code `-1`:

```javascript
switch (error.code) {
          case statusCodes.SIGN_IN_CANCELLED:
          case '-1':
            return Alert.alert('Google Auth Canceled');
          case statusCodes.IN_PROGRESS:
            return Alert.alert('Google Auth Already In Progress');
          case statusCodes.PLAY_SERVICES_NOT_AVAILABLE:
            return Alert.alert('Google Auth Requires Play Services');
          default:
            console.log('error', error);
            Alert.alert('Google Auth Error', error.message);
        }
```

**Comment by Salakar** [comment]
@Ross-Gibson thank you for reporting 🤗 all your reports have been super helpful

This has been added for the next update coming out in a few days, update will be available from your dashboard.
