### ISSUE TITLE
Google login is not possible for new users

### ISSUE THREAD

**Issue by Ross-Gibson** [react-native-market/firebase-authentication-kit#12]
Hello, I have an issue with my purchase (qOuutZdDkbgJcNW0UVXJ), here are the details of my issue:

This is a similar issue to #10.

 To resolve, update the `handleGoogle` function in `src/providers/Google.tsx` to this:

```javascript
async function handleGoogle() {
    if (!loading) {
      setLoading(true);

      try {
        await GoogleSignin.hasPlayServices();

        if (variant === 'UNLINK' && user) {
          await user.unlink(PROVIDER_ID);
        } else {
          await GoogleSignin.signIn();
          const {accessToken, idToken} = await GoogleSignin.getTokens();
          const credential = auth.GoogleAuthProvider.credential(
            idToken,
            accessToken,
          );

          if (variant === 'LINK' && user) {
            await user.linkWithCredential(credential);
          } else if (variant === 'SIGN_IN') {
            await auth().signInWithCredential(credential);
          }
        }
      } catch (error) {
        switch (error.code) {
          case statusCodes.SIGN_IN_CANCELLED:
          case '-1':
            return Alert.alert('Google Auth Canceled');
          case statusCodes.IN_PROGRESS:
            return Alert.alert('Google Auth Already In Progress');
          case statusCodes.PLAY_SERVICES_NOT_AVAILABLE:
            return Alert.alert('Google Auth Requires Play Services');
          default:
            console.log('error', error);
            Alert.alert('Google Auth Error', error.message);
        }
      } finally {
        setLoading(false);
      }
    }
  }
```

**Comment by missklorina** [comment]
Hi, when I try this code I get a Google Auth Error - DEVELOPER_ERROR. 
Does this code work for you?

**Comment by Ross-Gibson** [comment]
Hi @missklorina, yes the above code is working for me. It's only slightly different from the version shipped when you purchased a license - adding a fix for the `SIGN_IN_CANCELLED` status code, and checking for a `user`.

Are you sure that you've configured the Google SDK correctly in your project?

**Comment by missklorina** [comment]
At the start I was able to "link the google account" to an existing account, but implementing your code resulted in this error.
I will try to go deep to fix it if it's just mine, thanks @Ross-Gibson

**Comment by Ross-Gibson** [comment]
@missklorina are you getting this error on Android, iOS or both?

**Comment by missklorina** [comment]
@Ross-Gibson I'm developing only on Android for the moment.

**Comment by Ross-Gibson** [comment]
OK. @missklorina check that you have generated the SHA1 correctly and added it to Firebase.

**Comment by Salakar** [comment]
Hey @Ross-Gibson thanks for reporting this and for the code example to fix it, this will be available in the next update in a few days.

I've given you a 50% refund as a thanks
