### ISSUE TITLE
Bug Report - Can't use SIGN IN WITH FACEBOOK and SING IN WITH GOOGLE

### ISSUE THREAD

**Issue by missklorina** [react-native-market/firebase-authentication-kit#13]
After configuring all as the readme, I can't create new user through the facebook and google button.

The problem is located in the handler of google.tsx and facebook.tsx:
` async function handleGoogle() {
    if (!loading && user) {`

` async function handleFacebook() {
    if (!loading && user) {`

The user context is always null before the login.

**Comment by Ross-Gibson** [comment]
Hey @missklorina this is a duplicate of the issue I reported. I added some sample code to show how you can resolve this. Take a look at #10.

**Comment by missklorina** [comment]
Hi @Ross-Gibson, I saw your issues after that I created this.
I'm going to close it.
