### ISSUE TITLE
No logout button

### ISSUE THREAD

**Issue by sibijosephv** [react-native-market/firebase-authentication-kit#15]
No logout button in auth kit? 

That basic feature seems to be missing.

**Comment by Ross-Gibson** [comment]
Hey @sibijosephv the logout action is in `Settings.tsx`:

```javascript
async function signOut() {
    setSigningOut(true);
    await GoogleSignin.signOut();
    await auth().signOut();
  }
```

**Comment by Salakar** [comment]
@sibijosephv interesting, there should have been one from the draft spec we had - will get it added for the next update (in a few days, which you'll be able to download from your account again).

Will reply here when update is live with this fix.
