### ISSUE TITLE
How to extend the paper theme with typescript

### ISSUE THREAD

**Issue by ilibilibom** [react-native-market/firebase-authentication-kit#18]
Hi 
This is my theme.ts
```
export default {
  ...DefaultTheme,
  dark: false,
  roundness: 3,
  colors: {
    ...DefaultTheme.colors,
    primary: '#512da8',
    secondery: '#21c5d3',
    accent: '#fff',
    background: '#fff',
    buttonBackground: '#21C5D3',
  },
};
```

I've added new properties to this object. it workes fine but ts is saying that:
```
Property 'buttonBackground' does not exist on type '{ primary: string; background: string; surface: string; accent: string; error: string; text: string; disabled: string; placeholder: string; backdrop: string; }
```

Where do I add new property types? (I assume not in the paper - node modules folder)

**Comment by Salakar** [comment]
Theme types can't be extended, these are the type values you can specify: https://github.com/callstack/react-native-paper/blob/master/src/types.tsx#L26

In your case of `buttonBackground` paper automatically uses the primary colour, if you need to change it you can easily override it with the `color` prop on your `Button` instances: https://github.com/callstack/react-native-paper/blob/master/src/components/Button.tsx#L41

**Comment by ilibilibom** [comment]
@Salakar - Thanks, so isn't there a way to extend a TS interface?

**Comment by Salakar** [comment]
There is like I posted in the `User` issue, though paper expects an interface that matches their `Theme` interface.

You could just add another export in your `theme.ts` file and import that where you need to access your additional theme properties, e.g. 

```ts
// add to theme.ts
export const customColors = {
  buttonBackground: '#21C5D3',
};
```

import and use it:

```ts
import { customColors } from './theme.ts';

// e.g. use for the Button color prop
console.log(customColors.buttonBackground);
```
```

**Comment by ilibilibom** [comment]
@Salakar - thank you
