### ISSUE TITLE
Social login buttons don't work on login page

### ISSUE THREAD

**Issue by CiaranPearse** [react-native-market/firebase-authentication-kit#19]
I am able to create account with email/pass but when I click on 'Sign in with Facebook/Google' I see the button action but nothing happens. (expected screen or popup). No errors are displayed.

OSX using Iphone X and Android Nexus 2

**Comment by CiaranPearse** [comment]
Seems to be a duplicate of  #10 & #12

**Comment by Salakar** [comment]
> Seems to be a duplicate of #10 & #12

Sorry about these, these have been addressed in the next update coming out in a few days, you'll be able to get the updated kit from your account once it's live, please keep an eye out for the updated version appearing.

**Comment by ftx** [comment]
Any news for the update ? 
Thanks :)
