### ISSUE TITLE
IOS Installation not working

### ISSUE THREAD

**Issue by ilibilibom** [react-native-market/firebase-authentication-kit#2]
I'm trying to install the kit running ``` react-native run-ios``` 
the build fails - the error I'm getting (in xcode): 
``` 
duplicate symbol '_AuthErrorCode_toJSErrorCode' in:
    /Users/ilandiamond/Library/Developer/Xcode/DerivedData/app-czztfimhsfyvhwainacdfdiyczuu/Build/Products/Debug-iphonesimulator/RNFBAuth/libRNFBAuth.a(RNFBAuthModule.o)
    /Users/ilandiamond/Library/Developer/Xcode/DerivedData/app-czztfimhsfyvhwainacdfdiyczuu/Build/Products/Debug-iphonesimulator/RNFirebase/libRNFirebase.a(RNFirebaseAuth.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 
**Environment**
System:
OS: macOS 10.14.6
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 656.18 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.16.0 - /usr/local/bin/node
Yarn: 1.17.3 - /usr/local/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
Android SDK:
API Levels: 28, 29
Build Tools: 28.0.3, 29.0.2
System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 3.5 AI-191.8026.42.35.5791312
Xcode: 11.0/11A420a - /usr/bin/xcodebuild
npmPackages:
@react-native-community/cli: 2.9.0 => 2.9.0
react: 16.8.6 => 16.8.6
react-native: 0.60.5 => 0.60.5
npmGlobalPackages:
react-native-cli: 2.0.1

**Comment by Salakar** [comment]
Hey @ilibilibom - are you trying to install v5 RNFirebase along side v6 - they versions can't be mixed and are not cross compatible.

**Comment by ilibilibom** [comment]
@Salakar - I'm using the code that came with the kit I downloaded.
This is a new project

**Comment by Salakar** [comment]
@ilibilibom are you able to paste a copy of your package.json? Thanks

**Comment by Salakar** [comment]
Could you try the latest version of the product also please which I've just published - you can download it in your account section on the website. Thanks
