### ISSUE TITLE
duplicate symbol '_AuthErrorCode_toJSErrorCode

### ISSUE THREAD

**Issue by martinhudson** [react-native-market/firebase-authentication-kit#24]
Hi, I've installed firebase using the v6 installation guide and am returning the errors below when I compile for iOS:

_duplicate symbol '_AuthErrorCode_toJSErrorCode' in:
   .../Build/Products/Debug-iphonesimulator/RNFBAuth/libRNFBAuth.a(RNFBAuthModule.o)
   .../Build/Products/Debug-iphonesimulator/RNFirebase/libRNFirebase.a(RNFirebaseAuth.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)_

the relevant section of my package.json file is as follows:

"dependencies": {
    "@react-native-community/async-storage": "^1.6.3",
    "@react-native-firebase/analytics": "^6.0.0",
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/auth": "^6.1.0",
    "@react-native-firebase/crashlytics": "^6.0.0",
    "@react-native-firebase/messaging": "^6.1.0",
...

I tried clearing out my podfile and re-running pod install to no avail.

any advice would be appreciated.

**Comment by Salakar** [comment]
Hey @martinhudson 

```
../Build/Products/Debug-iphonesimulator/RNFBAuth/libRNFBAuth.a(RNFBAuthModule.o)
.../Build/Products/Debug-iphonesimulator/RNFirebase/libRNFirebase.a(RNFirebaseAuth.o)
```

Indicates to me that you had `react-native-firebase` v5 installed also along side v6, can't mix them unfortunately, I'd remove the `"react-native-firebase"` package from your dependencies if its there, delete your node_modules, yarn/npm install again from the root directory, and `pod install` again from the `ios` directory.

**Comment by nibinb** [comment]
Thanks Salakar.

I wasted 2 days just on this issue. I was first using cloud messaging from v5 and then i wanted authentication for which i was following v6 guide. Caused the same issue.
I am now fully switching to v5 cause i want push notifications on my app for which i cant find guides on v6(absolute newbie here).

**Comment by daheeahn** [comment]
> Hey @martinhudson
> 
> ```
> ../Build/Products/Debug-iphonesimulator/RNFBAuth/libRNFBAuth.a(RNFBAuthModule.o)
> .../Build/Products/Debug-iphonesimulator/RNFirebase/libRNFirebase.a(RNFirebaseAuth.o)
> ```
> 
> Indicates to me that you had `react-native-firebase` v5 installed also along side v6, can't mix them unfortunately, I'd remove the `"react-native-firebase"` package from your dependencies if its there, delete your node_modules, yarn/npm install again from the root directory, and `pod install` again from the `ios` directory.

You saved my day!! Thanks.
