### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by jason-cf** [react-native-market/firebase-authentication-kit#3]
I've followed the readme for the android installation, yet I still get this error when I try to run 'react-native run-android'

Workspace/RNFirebaseApp/node_modules/@react-native-firebase/app/android/src/main/java/io/invertase/firebase/common/UniversalFirebasePreferences.java:24: error: package io.invertase.firebase.app does not exist
import io.invertase.firebase.app.ReactNativeFirebaseApp;
                                ^
Workspace/RNFirebaseApp/node_modules/@react-native-firebase/app/android/src/main/java/io/invertase/firebase/common/UniversalFirebasePreferences.java:81: error: cannot find symbol
      preferences = ReactNativeFirebaseApp
                    ^
  symbol:   variable ReactNativeFirebaseApp
  location: class UniversalFirebasePreferences
2 errors

FAILURE: Build failed with an exception.

System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.72 GB / 23.21 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 8.16.1 - /usr/bin/node
    Yarn: 1.19.0 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-app-id: 0.0.5
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

**Comment by Salakar** [comment]
Hey @jason-cf thanks for reporting this - looks like this was an issue with the rename script - I've published a new version (0.0.2) of the product, if you can; please try it out - you can download it in your account purchases section on the website. Thanks

**Comment by jason-cf** [comment]
@Salakar, fyi, missing modules for fs-extra and replace-in-file, but otherwise, I was able to run the auth kit.



$ nodejs scripts/rename.js
module.js:550
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jason-work/Workspace/RNFirebaseApp-0.0.2/scripts/rename.js:2:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
