### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ftx** [react-native-market/firebase-authentication-kit#31]
Hello, I have an issue with my purchase (v1wqgzGqF2fF2Ra703hU), here are the details of my issue:

After have "npm install" and add ios & android firebase configuraitions files.
When i'm build and launch with xcode i have this error. : 

<img width="416" alt="Capture d’écran 2020-01-05 à 02 38 49" src="https://user-images.githubusercontent.com/1889424/71773857-ed23c180-2f64-11ea-9806-a7a348c5714a.png">

**Comment by ftx** [comment]
yarn add react-native-safe-area-view react-native-safe-area-context

**Comment by robbiew** [comment]
I had this error too... I don't think adding these repos worked.

 I think what solved was opening Xcode .workspace file, not the .project file? Then building.
