### ISSUE TITLE
IOS build fails

### ISSUE THREAD

**Issue by ilibilibom** [react-native-market/firebase-authentication-kit#5]
Hi 
The IOS build is failing with these messages:
```
/Users/me/Developer/Code/me/segundo/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Target Support Files/Pods-app/Pods-app.debug.xcconfig: unable to open file (in target "app" in project "app")
``` 
```
/Users/me/Developer/Code/me/segundo/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Target Support Files/Pods-appTests/Pods-appTests.debug.xcconfig: unable to open file (in target "appTests" in project "app")
```
``` 
/Users/me/Developer/Code/me/segundo/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Target Support Files/Pods-app/Pods-app.debug.xcconfig: unable to open file (in target "app" in project "app")
```
```
/Users/me/Developer/Code/me/segundo/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Target Support Files/Pods-app/Pods-app.debug.xcconfig: unable to open file (in target "app" in project "app")
```

**Comment by ilibilibom** [comment]
Hi
Any insights about this issue ??

**Comment by harrisrobin** [comment]
@ilibilibom did you run
`cd ios && pod install` ?

Also, you'll need to create a GoogleService-Info.plist in iOS folder. you might want to follow the instructions here: https://rnfirebase.io/docs/v5.x.x/installation/ios

That's the first step.

On another note, I do think this repo could have a readme for people who aren't aware that they have to link firebase.

**Comment by gmertk** [comment]
For me it was failing with `Pods/Pods...ProjectName.debug.xcconfig unable to open file`. Note that Pods part is duplicated.

https://stackoverflow.com/questions/55558984/xcode-pods-projectname-debug-xcconfig-unable-to-open-file-wrong-directory solved it.

- pod deintegrate
- pod install
- edit the .xcodeproj/project.pbxproj file and change the PBXGroup "path = Pods" to "name = Pods"

**Comment by sibijosephv** [comment]
info Building (using "xcodebuild -workspace mygrozery.xcworkspace -configuration Debug -scheme mygrozery -destination id=55E77AB9-1368-4BFA-B929-D7EB7580EB16 -derivedDataPath build/mygrozery")
................................
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mygrozery.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/build/mygrozery

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Pods/Target Support Files/Pods-mygrozery/Pods-mygrozery.debug.xcconfig: unable to open file (in target "mygrozery" in project "mygrozery") (in target 'mygrozery')

Build system information
error: /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Pods/Target Support Files/Pods-mygrozery/Pods-mygrozery.debug.xcconfig: unable to open file (in target "mygrozery" in project "mygrozery") (in target 'mygrozery')

Build system information
error: /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Pods/Target Support Files/Pods-mygrozery/Pods-mygrozery.debug.xcconfig: unable to open file (in target "mygrozery" in project "mygrozery") (in target 'mygrozery')

Build system information
error: /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Pods/Target Support Files/Pods-mygrozery/Pods-mygrozery.debug.xcconfig: unable to open file (in target "mygrozery" in project "mygrozery") (in target 'mygrozery')

Build system information
error: /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Pods/Target Support Files/Pods-mygrozeryTests/Pods-mygrozeryTests.debug.xcconfig: unable to open file (in target "mygrozeryTests" in project "mygrozery") (in target 'mygrozeryTests')

Build system information
error: /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Pods/Target Support Files/Pods-mygrozeryTests/Pods-mygrozeryTests.debug.xcconfig: unable to open file (in target "mygrozeryTests" in project "mygrozery") (in target 'mygrozeryTests')

Build system information
error: /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Pods/Target Support Files/Pods-mygrozeryTests/Pods-mygrozeryTests.debug.xcconfig: unable to open file (in target "mygrozeryTests" in project "mygrozery") (in target 'mygrozeryTests')

Build system information
error: /Users/sibij/Desktop/development/inprogress/rnm-firebase-authentication-kit-0.0.2/ios/Pods/Pods/Target Support Files/Pods-mygrozeryTests/Pods-mygrozeryTests.debug.xcconfig: unable to open file (in target "mygrozeryTests" in project "mygrozery") (in target 'mygrozeryTests')


** BUILD FAILED **

Please help.

**Comment by sibijosephv** [comment]
I followed these instructions

https://github.com/invertase/react-native-firebase-starter

**Comment by ilibilibom** [comment]
> @ilibilibom did you run
> `cd ios && pod install` ?
> 
> Also, you'll need to create a GoogleService-Info.plist in iOS folder. you might want to follow the instructions here: https://rnfirebase.io/docs/v5.x.x/installation/ios
> 
> That's the first step.
> 
> On another note, I do think this repo could have a readme for people who aren't aware that they have to link firebase.
> 
> good luck

@harrisrobin 
sorry for the late replay,
I did run pods install, and I do have the GoogleService-Info.plist file in place: 
The error that I'm getting now in the command line after running react-native run-ios is: 
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening app.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/build/app

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Multiple commands produce '/Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/build/app/Build/Products/Debug-iphonesimulator/app.app/GoogleService-Info.plist':
1) Target 'app' (project 'app') has copy command from '/Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/GoogleService-Info.plist' to '/Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/build/app/Build/Products/Debug-iphonesimulator/app.app/GoogleService-Info.plist'
2) Target 'app' (project 'app') has copy command from '/Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/app/GoogleService-Info.plist' to '/Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/build/app/Build/Products/Debug-iphonesimulator/app.app/GoogleService-Info.plist'

warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the app editor. (in target 'app' from project 'app')
warning: duplicate output file '/Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/build/app/Build/Products/Debug-iphonesimulator/app.app/GoogleService-Info.plist' on task: CopyPlistFile /Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/build/app/Build/Products/Debug-iphonesimulator/app.app/GoogleService-Info.plist /Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/app/GoogleService-Info.plist (in target 'app' from project 'app')

2019-10-29 09:50:34.038 XCBBuildService[49915:1664719] Failed to remove: /Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/build/app/Build/Intermediates.noindex/XCBuildData/83ab819c29e01f9d8886ced95df0d18a-desc.xcbuild: unlink(/Users/ilandiamond/Developer/Code/ilan/segundo/app/ios/build/app/Build/Intermediates.noindex/XCBuildData/83ab819c29e01f9d8886ced95df0d18a-desc.xcbuild): No such file or directory (2)
** BUILD FAILED **
```
Can you please help here

**Comment by sibijosephv** [comment]
Followed all the steps as before. No luck.

**Comment by jasonaliao** [comment]
Having the same issue. 
I've attempted [](https://stackoverflow.com/questions/55558984/xcode-pods-projectname-debug-xcconfig-unable-to-open-file-wrong-directory) but no luck.

**Comment by sibijosephv** [comment]
Too bad. No resolution for this issue for about a month. 

What is the point of buying this package if you can not provide proper support?
Can you please refund my money? 👎

**Comment by ilibilibom** [comment]
@harrisrobin

**Comment by harrisrobin** [comment]
@ilibilibom not really sure why it's failing for you.

Here are a few things you can try:

1. make sure GoogleService-Info.plist is in the right place in Xcode (make sure you use xworkspace file!)
<img width="695" alt="image" src="https://user-images.githubusercontent.com/3880008/67901919-5a1e7380-fb3e-11e9-82d0-2c618694122b.png">

2. here's what my AppDelegate.m looks like:
```
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <RNGoogleSignin/RNGoogleSignin.h>

@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

#pragma mark - Set up default firebase app
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

#pragma mark - Set up facebook SDK
  // Set up Facebook SDK
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self
                                            launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"FirebaseAuthenticationKit"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f
                                                    green:1.0f
                                                     blue:1.0f
                                                    alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
#if DEBUG
  return
      [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"
                                                     fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main"
                                 withExtension:@"jsbundle"];
#endif
}

#pragma mark - Handle incoming universal links
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:
                (NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {

  BOOL facebook = [[FBSDKApplicationDelegate sharedInstance]
            application:application
                openURL:url
      sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
             annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];

  BOOL google = [RNGoogleSignin application:application openURL:url options:options];

  return facebook || google;
}

@end
```

3. Don't forget to change your Bundle Identifier to something unique (make sure this part doesn't fail)
<img width="722" alt="image" src="https://user-images.githubusercontent.com/3880008/67901980-81754080-fb3e-11e9-920a-a2ac2dc9fa16.png">

4. just to be sure, go back in `iOS` folder and and run the following (make sure you ran `yarn` in the root first)

```
pod deintegrate
pod install --repo-update
```

Hope this helps, I didn't have to do anything other than the above assuming your GoogleService-Info.plist is valid and you've followed the steps on firebase.

**Comment by jasonaliao** [comment]
@sibijosephv I've got it working after re-installing yarn.

**Comment by ilibilibom** [comment]
@harrisrobin 
I'm starting my ios installation again from scratch. 
I want to do this step by step, to see that I'm doing all stages correctly.

1) on the Facebook ios app side, what do I define as bundle ID? 
![Screen Shot 2019-11-02 at 9 50 19](https://user-images.githubusercontent.com/12745414/68067899-95938a80-fd56-11e9-931c-3ef22d98459c.png)

**Comment by harrisrobin** [comment]
@ilibilibom the same as the one you defined in Xcode?

**Comment by ilibilibom** [comment]
@harrisrobin - 
OK - I got the build to run, I seem to have missed the ios Facebook readme section altogether. 
Thanks for your support.

**Comment by sibijosephv** [comment]
@jasonaliao  I could finally make it work. Thank you.

You should definitely have better documentation to bring down the number of support requests.

**Comment by Salakar** [comment]
> @sibijosephv You should definitely have better documentation to bring down the number of support requests.

What would you suggest is documented thats currently missing?

----

> @ilibilibom on the Facebook ios app side, what do I define as bundle ID?

Will update the docs to mention specifics on this bit. We're also working on making each login provider optional so you won't have to go through all the setup steps to get started (but that won't be out for a while yet - but lifetime updates so you'll be able to get updates either way)


----

> @harrisrobin make sure GoogleService-Info.plist is in the right place in Xcode (make sure you use xworkspace file!)

Thanks for helping out here. Side note; we have a download customisation system in the works where you can select (or create) the Firebase project you want to integrate and it'll install credentials for you so you can download the project ready to go.

----


Going to close this issue as it's resolved now and seems it was a case of a section of docs being skipped. Will keep an eye on the issue though for docs feedback suggestions.
