### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by sibijosephv** [react-native-market/firebase-authentication-kit#8]
Hello, I have an issue with my purchase (7nmYo3bq4GF47v3LIcsj), here are the details of my issue:

**Rename fails** Could not find any instructions. Can you please check this?

$ npm run rename
npm ERR! missing script: rename

$ npm run rename.js

npm ERR! missing script: rename.js
$ 
$ ls -l
total 16
-rw-r--r--@ 1 sibij  staff  7107 Oct  5 15:38 rename.js

**Comment by Salakar** [comment]
Hey, you need to run the script from the root of the project, not from the scripts directory

**Comment by sibijosephv** [comment]
Tried that. Getting the script missing error.

Sibis-MacBook-Air:grozerykit sibij$ npm run rename.js
npm ERR! missing script: rename.js
Sibis-MacBook-Air:grozerykit sibij$ npm run rename.js
npm ERR! missing script: rename.js

**Comment by sibijosephv** [comment]
Sibis-MacBook-Air:grozerykit sibij$ npm run rename
npm ERR! missing script: rename

**Comment by sibijosephv** [comment]
Sibis-MacBook-Air:rnm-firebase-authentication-kit-0.0.2 sibij$ npm run rename
npm ERR! missing script: rename

**Comment by Ehesp** [comment]
Could you show the output of `cat package.json` (or copy the package.json).

**Comment by gmertk** [comment]
Have you tried 

$ `npm run rename-project`

when you are in the root `rnm-firebase-authentication-kit-0.0.2` folder?

**Comment by sibijosephv** [comment]
npm run rename-project worked.

Thanks for your help.

But the build on ios fails. I will create a separate issue for that.
