### ISSUE TITLE
"npm run lint" doesn't check ts,tsx files

### ISSUE THREAD

**Issue by gmertk** [react-native-market/firebase-authentication-kit#9]
Hi folks,

Small issue which took some time for me to figure out:
In `package.json`, lint script is defined as `"lint": "eslint ."`. However eslint only check js files by default.

It might be better to define as `"lint": "eslint . --ext .ts,.tsx"` as the project is written in TypeScript.

Thanks for this project! It gave me a head start.

**Comment by Ehesp** [comment]
Thanks we will get this added!

**Comment by Salakar** [comment]
@gmertk thanks again for raising this, this will be on the next update in a few days
